name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta una vez al día a la medianoche UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: TU_USUARIO  # Reemplaza con tu usuario de GitHub
          outputs: dist/snake.svg
      - name: Upload animation
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist
