name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:  

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4  

      - name: Generar la animación de la serpiente
        uses: Platane/snk@v3
        with:
          github_user_name: LucasFleitas  
          outputs: dist/snake.svg

      - name: Subir el archivo generado
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/snake.svg
